In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3])

In [4]:
print(v)

[1 2 3]


In [5]:
print(v.shape)

(3,)


In [6]:
x = v.T

In [7]:
print(x)

[1 2 3]


In [8]:
print(x.shape)

(3,)


In [9]:
z = np.reshape(x,(3,1))

In [10]:
print(z)

[[1]
 [2]
 [3]]


In [11]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs
# displays the following result:
# array([[-0.27,  0.45,  0.64,  0.31]])


array([[-0.27,  0.45,  0.64,  0.31]])

In [12]:
inputs.shape
# displays the following result:
# (1, 4)

(1, 4)

In [13]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights
# displays the following result:
# array([[ 0.02 ,  0.001, -0.03 ,  0.036],
#        [ 0.04 , -0.003,  0.025,  0.009],
#        [ 0.012, -0.045,  0.28 , -0.067]])


array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [14]:
weights.shape
# displays the following result:
# (3, 4)

(3, 4)

In [15]:
np.matmul(inputs, weights)
# displays the following error:
# ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
np.matmul(inputs, weights.T)
# displays the following result:
# array([[-0.01299,  0.00664,  0.13494]])

In [ ]:
print(weights.T.shape)

In [ ]:
new = weights.T

In [ ]:
new


In [ ]:
print(new)

In [5]:
import numpy as np
test_w_h_o = np.array([[0.4850045],
                       [0.45512111]])

In [6]:
print(test_w_h_o)
print(test_w_h_o.shape)

[[ 0.4850045 ]
 [ 0.45512111]]
(2, 1)


In [7]:
print(test_w_h_o[:,0])

[ 0.4850045   0.45512111]


In [8]:
print(test_w_h_o[:,0].shape)

(2,)


In [30]:
test1 = np.array([-0.0291865582992])

In [31]:
out = test1 * test_w_h_o

In [32]:
print(out)

[[-0.01415561]
 [-0.01328342]]


In [33]:
print(test1.shape)

(1,)


In [34]:
print(out.shape)

(2, 1)
